### ISSUE TITLE
1.3.0

### ISSUE THREAD

**Issue by AaronDewes** [lncm/docker-specter-desktop#20]
Specter desktop 1.3.0 got just released, @nolim1t can you tag it here?

@lukechilds @mayankchhabra That's something we can (hopefully) quickly add to 0.3.9, so we also do something useful there.

**Comment by nolim1t** [comment]
Already done. 

I'll add you as maintainer for this project too @AaronDewes so you can tag things if things gets released during the late night in Asia.

I trust that you can handle this too. 

Just have to add a tag and push it.

Bonus would be also to create a pr and update the documentation too for consistency

**Comment by nolim1t** [comment]
Anyway you can now write to this project too @AaronDewes .. I think @lukechilds can also tag stuff already on this too (and any projects in the lncm org too)

**Comment by nolim1t** [comment]
Please test the following. My initial tests of the image is ok. I've managed to even sign and broadcast a transaction.

https://github.com/getumbrel/umbrel/pull/689
