### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by k9ert** [lncm/docker-specter-desktop#4]
Great work! Kudos to you guys. I've mentioned you in this PR:
https://github.com/cryptoadvance/specter-desktop/pull/480

Would be awesome if we could get your work directly into specter?! Lots of people already want docker-images and creating them just automatically with the release (and maybe in other ways manually) in the most convenient/automatic way would be awesome!

**Comment by k9ert** [comment]
Nevermind, i guess the right reason for closing this is "invalid". This is just so cool! Please let's have a chat at some time.

**Comment by nolim1t** [comment]
Sure .. the main magic in this repo is the deterministic building and pushing to docker repos but I've always considered pushing this to upstream too

**Comment by nolim1t** [comment]
> Nevermind, i guess the right reason for closing this is "invalid". This is just so cool! Please let's have a chat at some time.
> You can contact me on telegram, same handle: @k9ert

Ok, you can also reach out to me on telegram (same username too)
